"""Export the prompts group members gave Claude Code in this project, for llm_usage_21.pdf.

  .venv/bin/python tools/export_prompts.py [--out LLM_PROMPTS.md] [--projects-dir DIR]

Reads the Claude Code transcripts (~/.claude/projects/<this repo>/*.jsonl) and writes every user-typed
prompt plus answers to Claude's clarifying questions, in time order. Tool output, IDE context tags
and subagent traffic are left out. Dev tool only; never part of a bot.
"""
import argparse
import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DIR = os.path.expanduser('~/.claude/projects/' + re.sub(r'[^A-Za-z0-9]', '-', ROOT))
TAG_RE = re.compile(r'<(ide_[a-z_]+|system-reminder|task-notification)>.*?</\1>', re.S)
CMD_RE = re.compile(r'<command-name>(.*?)</command-name>\s*<command-args>(.*?)</command-args>', re.S)
AUTO_PREFIXES = ('<command-', '[Request interrupted', 'Caveat:', 'This session is being continued from a previous conversation')
ANSWER_MARKERS = ('Your questions have been answered', 'User has approved your plan', 'The user doesn\'t want')


def text_of(content):
    if isinstance(content, str):
        return content
    parts = []
    for c in content:
        if c.get('type') == 'text':
            parts.append(c.get('text', ''))
    return '\n'.join(parts)


def answers_of(content):
    out = []
    if isinstance(content, list):
        for c in content:
            if c.get('type') == 'tool_result':
                body = c.get('content')
                body = text_of(body) if isinstance(body, list) else (body or '')
                if body.startswith(ANSWER_MARKERS):
                    out.append(body.split('\n\n## Approved Plan')[0].strip())
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=os.path.join(ROOT, 'LLM_PROMPTS.md'))
    ap.add_argument('--projects-dir', default=DEFAULT_DIR)
    a = ap.parse_args()
    items = []
    for path in glob.glob(os.path.join(a.projects_dir, '*.jsonl')):
        session = os.path.basename(path)[:8]
        with open(path) as f:
            for line in f:
                try:
                    d = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if d.get('type') != 'user' or d.get('isSidechain') or d.get('isMeta'):
                    continue
                content = d.get('message', {}).get('content')
                ts = d.get('timestamp', '')
                txt = TAG_RE.sub('', text_of(content) if content else '').strip()
                m = CMD_RE.search(txt)
                if m:
                    txt = (m.group(1) + ' ' + m.group(2)).strip()
                    items.append((ts, session, 'prompt', txt))
                elif txt and not txt.startswith(AUTO_PREFIXES):
                    items.append((ts, session, 'prompt', txt))
                for ans in answers_of(content or []):
                    items.append((ts, session, 'answer', ans))
    items.sort()
    with open(a.out, 'w') as f:
        f.write('# LLM usage: prompts given to Claude Code (CITS3011 group 21)\n\n')
        f.write(f'Generated by tools/export_prompts.py from {len(glob.glob(os.path.join(a.projects_dir, "*.jsonl")))}'
                f' transcript(s). Tool: Claude Code (Anthropic).\n\n')
        for ts, session, kind, txt in items:
            f.write(f'## {ts[:16].replace("T", " ")} UTC — session {session} — {kind}\n\n')
            f.write('\n'.join('> ' + ln for ln in txt.splitlines()) + '\n\n')
    print(f'wrote {len(items)} entries to {a.out}')


if __name__ == '__main__':
    main()
